GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxjYW1pdDBAZ21haWwuY29tIiwiaWF0IjoxNTEyNTM0NjkyLCJleHAiOjE1MTMxMzk0OTIsInN1YiI6IjVhMjc1MGQ5NTE1NzFkOTg4Y2ViYTJhMiJ9.FVEdNPrxRS9CkP1N2W-USPnRWqfSSjvYmiX0_5yvo5w 

###

POST http://localhost:7000/auth/register
Content-Type: application/json

{
    "email": "carlcamit0@gmail.com",
    "firstName": "Carl",
    "lastName": "Camit",
    "password": "password123"
}

###

POST http://localhost:7000/auth/signin
Content-Type: application/json

{
    "email": "carlcamit0@gmail.com",
    "password": "password123"
}