GET http://localhost:7000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhcmxjYW1pdDBAZ21haWwuY29tIiwiaWF0IjoxNTEyNjI3MDk2LCJleHAiOjE1MTMyMzE4OTYsInN1YiI6IjVhMjhiYmM4NjkzNjk3YjJlZjdmZDNlMiJ9.EwP1gclp_Yx0vwVnk8AIrV5k9fau8uVu3CEKs4-8exg

###

DELETE http://localhost:7000/products/5a28e26d20aefab98130b0ef

###

GET http://localhost:7000/auth

###

POST http://localhost:7000/auth/register
Content-Type: application/json

{
    "email": "carlcamit01@gmail.com",
    "firstName": "Carl",
    "lastName": "Camit",
    "password": "password123"
}

###

POST http://localhost:7000/auth/signin
Content-Type: application/json

{
    "email": "carlcamit0@gmail.com",
    "password": "password123"
}